version: '3.9'
networks:
  dev:
    external: true

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "${DJANGO_PORT}:8000"
    command: "sh /entrypoint.sh"
    env_file:
     - ../.env
    depends_on:
     - postgres
    volumes:
      - ..:/app/
      - staticfiles:/app/static
    networks:
      - dev


volumes:
  staticfiles:
